apiVersion: v2
name: jupyter-r
description: The JupyterLab IDE with R and a collection of standard data science packages.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
- Jupyter
- Python
home: https://jupyter.org/
sources:
- https://github.com/InseeFrLab/images-datascience
- https://github.com/InseeFrLab/helm-charts-interactive-services
type: application
version: 1.13.16
dependencies:
- name: library-chart
  version: 1.5.16
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
