global:
  suspend: false
service:
  image:
    version: inseefrlab/onyxia-jupyter-r:r4.4.1
    pullPolicy: IfNotPresent
    custom:
      enabled: false
      version: inseefrlab/onyxia-jupyter-r:r4.4.1
security:
  password: changeme
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
  personalInit: ''
  personalInitArgs: ''
environment:
  user: onyxia
  group: users
s3:
  enabled: false
  configMapName: ''
  accessKeyId: ''
  endpoint: ''
  defaultRegion: ''
  secretAccessKey: ''
  sessionToken: ''
vault:
  enabled: false
  configMapName: ''
  token: ''
  url: ''
  mount: ''
  secret: ''
  directory: ''
git:
  enabled: false
  configMapName: ''
  name: ''
  email: ''
  cache: ''
  token: ''
  repository: ''
  branch: ''
repository:
  configMapName: ''
  pipRepository: ''
  condaRepository: ''
discovery:
  hive: true
  mlflow: true
  metaflow: true
hive:
  configMapName: ''
mlflow:
  configMapName: ''
coresite:
  configMapName: ''
metaflow:
  configMapName: ''
replicaCount: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
kubernetes:
  enabled: false
  role: view
podAnnotations: {}
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8888
  user:
    enabled: false
    port: 5000
  sparkui:
    port: 4040
ingress:
  enabled: false
  tls: true
  ingressClassName: ''
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  useCertManager: false
  certManagerClusterIssuer: ''
route:
  enabled: false
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
  wildcardPolicy: None
resources: {}
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
userPreferences:
  darkMode: false
  language: en
openshiftSCC:
  enabled: false
  scc: ''
proxy:
  enabled: false
  noProxy: ''
  httpProxy: ''
  httpsProxy: ''
message:
  fr: ''
  en: ''
