# A template to prepull some images and then pause for ever
# Source : https://github.com/kubernetes/kubernetes/issues/36601#issuecomment-596202933
apiVersion: apps/v1
kind: ""
metadata:
  name: prepull
  labels:
    name: ""
spec:
  selector:
    matchLabels:
      name: ""
  template:
    metadata:
      labels:
        name: "" 
    spec:
      initContainers: []
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
