{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  serviceName: {{ include "library-chart.fullname" . }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if (include "library-chart.repository.enabled"  .) }}
        checksum/repository: {{ include (print $.Template.BasePath "/configmap-repository.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.s3.enabled }}
        checksum/s3: {{ include (print $.Template.BasePath "/configmap-s3.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: home
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "library-chart.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.spark.default }}
        - name: config-sparkconf
          configMap:
            name: {{ include "library-chart.configMapNameSparkConf" . }}
        {{- end }}
        {{- if and (.Values.spark.default) (.Values.repository.mavenRepository) }}
        - name: config-ivysettings
          configMap:
            name: {{ include "library-chart.configMapNameIvySettings" . }}
        {{- end }}
        {{- if .Values.discovery.hive }}
        - name: hive-config
          configMap:
            name: {{ include "library-chart.configMapNameHive" . }}
        {{- end }}
        {{- if .Values.discovery.metaflow }}
        - name: metaflow-config
          configMap:
            name: {{ include "library-chart.configMapNameMetaflow" . }}
        {{- end }}
        {{- if .Values.s3.enabled }}
        - name: config-coresite
          configMap:
            name: {{ include "library-chart.configMapNameCoreSite" . }}
        {{- end }}
        - name: config-tmp
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      subdomain: {{ include "library-chart.fullname" . }}
      hostname: jupyter
      initContainers:
        - name: make-configmaps-writable
          image: alpine
          command: ['sh', '-c', 'cp /src/hive-site.xml /dest/hive-site.xml']
          volumeMounts:
            - name: hive-config
              mountPath: /src
            - name: config-tmp
              mountPath: /dest
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.service.image.custom.enabled }}
          image: "{{ .Values.service.image.custom.version }}"
          {{- else }}
          image: "{{ .Values.service.image.version }}"
          {{- end }}
          command: ["/bin/sh","-c"]
          args: ["{{ .Values.init.standardInitPath }} jupyter lab --no-browser --ip '0.0.0.0' --LabApp.token='$(PASSWORD)' --ContentsManager.allow_hidden=True"]
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          env:
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_NAME
              {{- if .Values.service.image.custom.enabled }}
              value: "{{ .Values.service.image.custom.version }}"
              {{- else }}
              value: "{{ .Values.service.image.version }}"
              {{- end }}
            - name: NB_USER
              value: {{ .Values.environment.user }}
            - name: PASSWORD
              value: {{ .Values.security.password }}
            - name: PROJECT_USER
              value: {{ .Values.environment.user }}
            - name: PROJECT_GROUP
              value: {{ .Values.environment.group }}
            - name: ROOT_PROJECT_DIRECTORY
              value: /home/{{ .Values.environment.user }}/work
            {{- if .Values.init.regionInit }}
            - name: REGION_INIT_SCRIPT
              value: {{ .Values.init.regionInit }}
            {{- end }}
            {{- if .Values.init.personalInit }}
            - name: PERSONAL_INIT_SCRIPT
              value: {{ .Values.init.personalInit }}
            {{- end }}
            {{- if .Values.init.personalInitArgs }}
            - name: PERSONAL_INIT_ARGS
              value: {{ .Values.init.personalInitArgs }}
            {{- end }}
            {{- if .Values.environment.root }}
            - name: GRANT_SUDO
              value: "yes"
            {{- end }}          
          envFrom: 
            {{- if .Values.s3.enabled }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameS3" . }}
            {{- end }}
            {{- if .Values.vault.enabled }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameVault" . }}
            {{- end }}
            {{- if .Values.git.enabled }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameGit" . }}
            {{- end }}
            {{- if (include "library-chart.repository.enabled"  .) }}
            - configMapRef:
                name: {{ include "library-chart.configMapNameRepository" . }}
            {{- end }}
            {{- if not (empty (trim (include "library-chart.configMapMLFlow" .)))}}
            - configMapRef:
                name: {{ include "library-chart.configMapNameMLFlow" . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.networking.service.port }}
            {{- toYaml .Values.startupProbe | nindent 12 }}     
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/{{ .Values.environment.user}}/work
              subPath: work
              name: home
            {{- if .Values.s3.enabled }}
            - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: config-coresite
            {{- end }}
            {{- if .Values.spark.default }}
            - name: config-sparkconf
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            {{- end }}
            {{- if and (.Values.spark.default) (.Values.repository.mavenRepository) }}
            - name: config-ivysettings
              mountPath: /opt/spark/conf/ivysettings.xml
              subPath: ivysettings.xml
            {{- end }}
            {{- if .Values.discovery.hive }}
            - name: config-tmp
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            {{- end }}       
            {{- if .Values.discovery.metaflow }}
            - name: metaflow-config
              mountPath: /home/{{ .Values.environment.user}}/.metaflowconfig/config.json
              subPath: config.json
            {{- end }}   
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
